CocktailMagicianWeb/Models/Bars/BarResultsViewModel.cs
using System.Collections.Generic;

namespace CocktailMagicianWeb.Models
{
    public class BarResultsViewModel
    {
        public List<BarViewModel> Bars { get; set; }
    }
}

CocktailMagicianWeb/Models/Bars/BarSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Models
{
    public class BarSearchViewModel
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public double? AvgRating { get; set; }
        public bool ShowOnlyHiddenFiles { get; set; }
        public IReadOnlyCollection<BarViewModel> SearchResults { get; set; }
    }
}

CocktailMagicianWeb/Models/Bars/BarViewModel.cs
using CocktailMagician.Data.Entities;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Models
{
    public class BarViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter an address")]
        public string Address { get; set; }
        [RegularExpression("([0-9]+)", ErrorMessage = "Please enter valid Number")]
        [Required(ErrorMessage = "Please enter a number")]
        public string PhoneNumber { get; set; }
        public IFormFile NewPicture { get; set; }
        public byte[] CurrentPicture { get; set; }
        public bool IsHidden { get; set; }
        public List<BarReview> BarReviews { get; set; } = new List<BarReview>();
        public virtual List<string> Cocktails { get; set; } = new List<string>();
        public double Rating { get; set; }
        public string GeoCoderApiTemplate { get; set; }
        public string GeoCoderApiQuerySeparator { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public string ImageAddress { get; set; }

        public BarViewModel()
        {
            GeoCoderApiTemplate = "https://nominatim.openstreetmap.org/search?q={0}&accept-language=en&format={1}&addressdetails=1&limit={2}&polygon_svg=1&email=lssah@protonmail.com";
            GeoCoderApiQuerySeparator = "+";
        }
        public BarViewModel(Bar bar)
        {
            GeoCoderApiTemplate = "https://nominatim.openstreetmap.org/search?q={0}&accept-language=en&format={1}&addressdetails=1&limit={2}&polygon_svg=1&email=lssah@protonmail.com";
            GeoCoderApiQuerySeparator = "+";


            Id = bar.Id;
            IsHidden = bar.IsHidden;
            Name = bar.Name;
            CurrentPicture = bar.Picture == null ? new byte[0] : bar.Picture;
            Address = bar.Address;
            PhoneNumber = bar.PhoneNumber;
            Lat = bar.Lat;
            Long = bar.Long;
            Cocktails = bar.BarCocktails == null ? new List<string>() : bar.BarCocktails.Select(x => x.Cocktail.Name).ToList();
            try
            {
                Rating = Math.Round(bar.BarReviews.Select(b => b.Rating).Average(), 2);
            }
            catch (Exception)
            {
                Rating = 0;
            }
            ImageAddress = ParseStaticGoogleMapQuery();
        }

        public string FormQuery(string[] queryParams)
        {
            return string.Join(GeoCoderApiQuerySeparator, queryParams);
        }

        public string FormatApiTemplate(string[] queryParams)
        {
            var parsedQuery = FormQuery(queryParams);
            return string.Format(GeoCoderApiTemplate, parsedQuery, "json", 1);
        }

        public void ParseApiResult(string apiResultAsString)
        {
            if (string.IsNullOrEmpty(apiResultAsString) || apiResultAsString == "[]")
            {
                this.Lat = 0;
                this.Long = 0;
                return;
            }

            var apiStringToJArr = JsonConvert.DeserializeObject<JArray>(apiResultAsString);
            var firstResultJObj = apiStringToJArr.First().ToObject<JObject>();

            foreach (JProperty item in firstResultJObj.Children())
            {
                if (item.Name == "lat")
                {
                    this.Lat = Convert.ToDecimal(item.Value);
                }
                else if (item.Name == "lon")
                {
                    this.Long = Convert.ToDecimal(item.Value);
                }
            }
        }

        public string ParseStaticGoogleMapQuery()
        {
            return string.Format(@"https://maps.googleapis.com/maps/api/staticmap?center={0},{1}
                   &zoom=13
                   &size=600x300
                   &maptype=roadmap
                   &markers=color:red%7Clabel:S%7C{0},{1}
                   &key=AIzaSyD4TQy6H8TRVuUU7jQvC-mXOw7VPdD_iyk", this.Lat, this.Long);
        }
    }

}

CocktailMagicianWeb/Models/Bars/CreateBarViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Models.Bars
{
    public class CreateBarViewModel
    {
        public BarViewModel BarResult { get; set; }
        public IFormFile PictureBar { get; set; }
    }
}

CocktailMagicianWeb/Controllers/BarController.cs
using CocktailMagician.Services.Contracts;
using CocktailMagicianWeb.Models;
using CocktailMagicianWeb.Models.Cocktails;
using CocktailMagicianWeb.Utilities.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Controllers
{
    public class BarController : Controller
    {
        private readonly IBarServices _barServices;
        private readonly ICocktailServices _cocktailServices;
        private readonly IBarCocktailServices _barCocktailServices;
        private readonly IApiServices _apiServices;
        private readonly IFormattingService _formattingService;
        private readonly IMailServices _mailServices;

        public BarController(IBarServices barServices, ICocktailServices cocktailServices, IBarCocktailServices barCocktailServices, IApiServices apiServices, IFormattingService formattingService, IMailServices mailServices)
        {
            _barServices = barServices;
            _cocktailServices = cocktailServices;
            _barCocktailServices = barCocktailServices;
            _apiServices = apiServices;
            _formattingService = formattingService;
            _mailServices = mailServices;
        }

        [HttpGet]
        [Authorize(Roles = "CocktailMagician")]
        public IActionResult CreateBar()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> CreateBar(BarViewModel barViewModel)
        {
            if (await _barServices.BarWithThatNameExists(barViewModel.Name))
            {
                ModelState.AddModelError(string.Empty, "Bar with that name already exists.");
                return View();
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            var query = barViewModel.FormatApiTemplate(barViewModel.Address.Split(' '));
            var apiResult = await this._apiServices.CallApiAsync(query);
            barViewModel.ParseApiResult(apiResult);
            var barModel = await barViewModel.MapToEntity();
            await _barServices.CreateBarAsync(barModel);
            foreach (var cocktail in barViewModel.Cocktails)
            {
                var cocktailEntity = await _cocktailServices.GetAsync(cocktail);
                await _barCocktailServices.CreateAsync(barModel, cocktailEntity);
            }
            return View("BarDetails",barViewModel);
        }
        [Authorize(Roles = "CocktailMagician")]

        public async Task<IActionResult> ManageBars(BarSearchViewModel vm)
        {
            if (string.IsNullOrEmpty(vm.Name))
            {
                return View();
            }

            vm.SearchResults = (await _barServices.GetMultipleBarsByNameAsync(vm.Name)).Select(b => b.MapToViewModel()).ToList();
            if (vm.SearchResults.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "No bars found with this name.");
                return View();
            }

            return View(vm);
        }
        public IActionResult TestView()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SearchBars()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchBars(BarSearchViewModel viewModel)
        {
            if (viewModel.AvgRating != null)
            {
                viewModel.SearchResults = (await this._barServices.SearchBarsByMultipleCriteriaAsync(viewModel.Name, viewModel.Address, viewModel.PhoneNumber, viewModel.ShowOnlyHiddenFiles)).Select(b => b.MapToViewModel()).Where(b => b.Rating == viewModel.AvgRating).ToList();
            }
            else
            {
                viewModel.SearchResults = (await this._barServices.SearchBarsByMultipleCriteriaAsync(viewModel.Name, viewModel.Address, viewModel.PhoneNumber, viewModel.ShowOnlyHiddenFiles)).Select(b => b.MapToViewModel()).ToList();
            }
            return View(viewModel);

        }
        [HttpGet]
        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> EditBar(int id)
        {
            var viewmodel = (await this._barServices.GetBarAsync(id)).MapToViewModel();

            return View(viewmodel);
        }
        [HttpPost]
        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> EditBar(BarViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var bar = await viewModel.MapToEntity();
            await this._barServices.EditBarAsync(bar);
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public async Task<IActionResult> BarDetails(int Id)
        {
            var bar = await this._barServices.GetBarAsync(Id);
            var viewModel = new BarViewModel(bar);
            return View(viewModel);
        }

        public async Task<IActionResult> GetBars(string type)
        {
            var bars = await _barServices.GetCollectionAsync();
            return Json(bars);
        }
        public async Task<IActionResult> LoadMoreCocktails([FromQuery]int Loaded, [FromQuery]int id)
        {
            var cocktails = await _barServices.LoadMoreCocktails(Loaded, id);
            return Json(cocktails);
        }

        public async Task<IActionResult> NameExists(string name)
        {
            var boolCheck = await _barServices.BarWithThatNameExists(name);
            return Json(boolCheck);
        }
        public async Task HideBar([FromBody]BarViewModel vm)
        {
            await _barServices.HideAsync(vm.Id);
        }

        public async Task UnhideBar([FromBody]BarViewModel vm)
        {
            await _barServices.UnhideAsync(vm.Id);
        }
        [HttpGet]
        public async Task<IActionResult> GetBarEventPartial(int id)
        {
            var bar = await _barServices.GetBarAsync(id);
            return PartialView("_CreateEventPartial", new EventViewModel(bar));
        }

        [HttpPost]
        public async Task<IActionResult> CreateBarEvent(EventViewModel model)
        {
            string modelAsString = string.Empty;

            var bar = await _barServices.GetBarAsync(model.BarId);
            var cocktailViewModel = new CocktailsViewModel();
            cocktailViewModel.Cocktails = bar.BarCocktails.Select(bc => bc.Cocktail.MapToViewModel()).ToList();
            try
            {
                model.BarViewHtmlString = await _formattingService.RenderViewToStringAsync<CocktailsViewModel>("_BarMenuPartial",cocktailViewModel);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            var emails = model.InvitationEmailAddresses.TrimEnd('x').Split(new char[] { 'x', ',' }, StringSplitOptions.None);
            var from = "vesselinignatoff88@gmail.com";
            var body = model.ToString();
            var subject = "Event invitation";
            var viewAsPdf = _formattingService.HtmlStringToPDF(model.BarViewHtmlString);

            bool mailsSent = await _mailServices.SendEmailToGroup(from, emails, subject, body, viewAsPdf);

            // тука може да си добавите сървис, който да запазва ивента в базата. в момента нямам имплементиран такъв сървис, нито имам ентити за ивент, има само ивентвюмодел
            // може в джейсъна да сложите и още пропъртита за да има за всяка операция.



            // bool successfullyCreated = this.eventServices.CreateAsync(model);  => псевдо код как запазвате ивента в базата и ако е успешно може да върнете от сървиса тру, иначе фолс и
            // така може да пратите инфо в джейсъна за всичките неща - и за статуса на мейлите и за статуса на самия ивент

            return Json(new { mailsSent = mailsSent/*, successfullyCreated = successfullyCreated*/ });

        }
    }
}

CocktailMagicianWeb/Controllers/ReviewsController.cs
using CocktailMagician.Data.Entities;
using CocktailMagician.Services.Contracts;
using CocktailMagicianWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Controllers
{

    public class ReviewsController : Controller
    {
        private readonly IBarServices _barServices;
        private readonly IBarReviewServices _barReviewServices;
        private readonly ICocktailReviewServices _cocktailReviewServices;
        private readonly ICocktailServices _cocktailServices;
        private readonly UserManager<User> _userManager;

        public ReviewsController(IBarServices barServices, IBarReviewServices barReviewServices, ICocktailReviewServices cocktailReviewServices, ICocktailServices cocktailServices, UserManager<User> userManager)
        {
            _barServices = barServices;
            _barReviewServices = barReviewServices;
            _cocktailReviewServices = cocktailReviewServices;
            _cocktailServices = cocktailServices;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpGet]
        public async Task<IActionResult> LeaveBarReview(int Id)
        {
            var viewModel = new ReviewViewModel
            {
                Id = Id,
            };
            return View(viewModel);
        }
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpPost]
        public async Task<IActionResult> LeaveBarReview(ReviewViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var bar = await _barServices.GetBarAsync(viewModel.Id);
            await _barReviewServices.CreateBarReviewAsync(viewModel.Rating, viewModel.Comment, bar, user);
            return RedirectToAction("Index", "Home");
        }
 
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpGet]
        public IActionResult LeaveCocktailReview(int Id)
        {
            var viewModel = new ReviewViewModel
            {
                Id = Id,
            };
            return View(viewModel);
        }
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpPost]
        public async Task<IActionResult> LeaveCocktailReview(ReviewViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var cocktail = await _cocktailServices.GetAsync(viewModel.Id);
            await _cocktailReviewServices.CreateCocktailReviewAsync(viewModel.Rating, viewModel.Comment, cocktail, user);
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> LoadCoctailReviews(int id)
        {
            var cocktailReviews = await _cocktailReviewServices.GetCocktailReviewsCollectionAsync(id);
            return PartialView("_LoadedCocktailReviewsPartial", cocktailReviews);
        }
        public async Task<IActionResult> LoadBarReviews(int id)
        {
            var reviews = await _barReviewServices.GetBarReviewsCollectionAsync(id);
            return PartialView("_LoadedBarReviewsPartial", reviews);
        }
    }
}

CocktailMagicianWeb/Views/Bar/BarDetails.cshtml
@model BarViewModel
@{
    ViewData["Title"] = "BarDetails";
    <style>

        body {
            background-image: url('../../images/37f072eb4f9453169d16478007277a1d.jpg');
            background-size: cover;
        }

        img {
            max-width: 100%;
            height: auto;
        }

        .BackgroundOpacity {
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 35px 35px;
            margin: 20px;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        tr {
            background-color: #f2f2f2
        }

        th {
            background-color: #ff0000;
            color: white;
        }

        .buttonReview {
            background: #ff0000;
            margin: 5px;
            width: 80%;
            color: white;
        }

        .margingaps {
            margin: 5px;
        }

        .barDesc {
            background-color: #ff0000;
            color: white;
        }

        h2 {
            margin-top: 50px;
            margin-left: 20px;
            font-size: 50px;
        }

        .modal-header {
            height: 80px;
            margin: 0;
        }

        /*.directionsIcons {
            margin: 0;
            height: inherit;
            display: inline-block;
        }*/
        #active-travel-mode {
            font-size: 48px;
            color: white;
            background-color: #dc3545;
            height: auto;
            padding: 3px;
            width: 20%;
            text-align: center;
            border-radius: 5px;
        }

        .fas {
            font-size: 48px;
            color: black;
            margin: 0;
            height: auto;
            padding: 3px;
            width: 20%;
            text-align: center;
            border-radius: 5px;
        }

            .fas:hover {
                font-size: 48px;
                color: white;
                background-color: rgba(220, 53, 69, 0.7);
            }

        .defaultMap {
            background-image: url("https://cdn1.iconfinder.com/data/icons/location-28/512/Untitled-67-512.png");
            background-size: cover;
        }
    </style>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <link href="~/css/BarDetailsGrid.css" rel="stylesheet" />
}
<h2 class="cola">Bar Details</h2>
<div class="grid-container">
    <div class="desctipion BackgroundOpacity">
        <div class="picture margingaps">
            @if (Model.CurrentPicture != null)
            {
                <img src="data:image/jpg;base64,@(Html.Raw(Convert.ToBase64String(Model.CurrentPicture)))" width="500" height="390" />

            }
            else
            {
                <img src="~/images/no-image-icon-6.png" width="230" height="172" />
            }
        </div>
        <div class="cocktails margingaps">
            <table class="table table">
                <th>Cocktails</th>
                <tr id="cocktailsTable">
                    <td id="InputCocktails">
                        @foreach (var cocktails in Model.Cocktails)
                        {
                            <p class="hakunaMatata">
                                @cocktails
                            </p>
                        }
                    </td>

                </tr>
            </table>
            @if (Model.Cocktails.Count == 10)
            {
                <button id="load-more-cocktails" data-id="@Model.Id">Load More</button>
            }

        </div>

        <div class="googlemaps" id="googlemaps" data-lat="@Model.Lat" data-lng="@Model.Long">

        </div>

        <div class="info margingaps">
            <table class="table table">
                @if (Model != null)
                {
                    <tr>
                        <td class="barDesc">Name:</td>
                        <td>
                            @Model.Name
                        </td>
                    </tr>
                    <tr>
                        <td class="barDesc">Adress:</td>
                        <td>
                            @Model.Address
                        </td>

                    </tr>
                    <tr>
                        <td class="barDesc">Phone Number:</td>
                        <td>
                            @Model.PhoneNumber
                        </td>
                    </tr>
                    <tr>
                        <td class="barDesc">Rated:</td>
                        <td>@Model.Rating</td>
                    </tr>
                }
            </table>
        </div>
        <div class="buttons">

            <button class="btn buttonReview" color:white" id="Load-Bars-Reviews" data-bar="@Model.Id">Load Reviews</button>
            @if (User.IsInRole("BarCrawler") || User.IsInRole("CocktailMagician"))
            {
                <button class="btn buttonReview" color:white" onclick="location.href='@Url.Action("LeaveBarReview", "Reviews", new { Id = Model.Id })'">Leave Review</button>
            }
        </div>
        <button class="btn buttonReview" id="createEvent" data-url="/Bar/GetBarEventPartial/@Model.Id">Create Event</button>
        <button class="btn getDirectionsBtn buttonReview" type="button" data-lat="@Model.Lat" data-lng="@Model.Long">Get Directions</button>
    </div>
    <div id="commentBox" class="comments">

    </div>
</div>

<div class="modal fade" id="directionsMapModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="width:100%;">
                <i class='fas fa-car-alt travelModeIcon' id="active-travel-mode" data-mode="DRIVING"></i>
                <i class='fas fa-bicycle travelModeIcon' data-mode="BICYCLING"></i>
                <i class='fas fa-bus-alt travelModeIcon' data-mode="TRANSIT"></i>
                <i class='fas fa-walking travelModeIcon' data-mode="WALKING"></i>
            </div>
            <div class="modal-body" id="modal-body" style="max-height:70%; height:500px;">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="closeModalBtn">Close</button>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="barEventForm">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="closeInvitationModalBtn">Close</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{


    <script>
        var map;
        var lat;
        var lng;
        var image;

        function initMap() {

            var mapElements = document.getElementById('googlemaps');
            var lat;
            var lng;

            const directionService = new google.maps.DirectionsService();
            const directionDisplay = new google.maps.DirectionsRenderer();



            lat = mapElements.dataset.lat;
            lng = mapElements.dataset.lng;

            if (lat == 0 || lng == 0) {
                mapElements.className = 'defaultMap';
                return;
            }

            var coordinates = new google.maps.LatLng(lat, lng);

            map = new google.maps.Map(mapElements, {
                zoom: 16,
                center: coordinates,
            });

            var markerSetup =
            {
                coords: coordinates,
                iconImage: image,
                content: false,
            };
            addMarker(markerSetup);


            function addMarker(props) {
                var marker = new google.maps.Marker({
                    position: props.coords,
                    map: map,
                });
                if (props.iconImage) {

                    marker.setIcon(props.iconImage);
                }

                if (props.content) {
                    var infoWindow = new google.maps.InfoWindow({
                        content: props.content
                    });
                }
            }

        }

        function initDirections(lat, lng, travelMode) {
            debugger;
            var modal = document.getElementById('directionsMapModal');
            const defaultTravelMode = 'DRIVING';

            if (typeof travelMode === "undefined" || travelMode === null) {
                travelMode = defaultTravelMode;
            }

            if (typeof lng === "undefined" || lng === null) {
                lng = modal.getAttribute('data-lng');
            }

            if (typeof lat === "undefined" || lat === null) {
                lng = modal.getAttribute('data-lat');
            }
            debugger;
            console.log(travelMode);
            const directionService = new google.maps.DirectionsService();
            const directionDisplay = new google.maps.DirectionsRenderer();
            var newCoordinates = [];
            var currentCoordinates = [];

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    newCoordinates = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    currentCoordinates = {
                        lat: parseFloat(lat),
                        lng: parseFloat(lng)
                    };


                    var request = {
                        origin: newCoordinates,
                        destination: currentCoordinates,
                        travelMode: travelMode
                    };


                    var modalBody = document.getElementById('modal-body');
                    var newMap = new google.maps.Map(modalBody, {
                        zoom: 30,
                        center: currentCoordinates,
                    });
                    directionDisplay.setMap(newMap)
                    directionService.route(request, (result, status) => {
                        if (status == 'OK') {

                            directionDisplay.setDirections(result);
                        }
                        if (status != 'OK' && travelMode == 'DRIVING') {
                            debugger;
                            return;
                        }
                        if (status == 'OK' || travelMode == 'DRIVING') {

                            debugger;
                            return;
                        }
                        else {
                            debugger;
                            toastr.error(`No suitable ${travelMode} routes were found for this direction\nMap is set to 'driving' travel mode`)
                            changeTravelModeByData(defaultTravelMode);
                            initDirections(lat, lng, defaultTravelMode);
                        }
                    });
                });
            }
        };
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyABQoWn57RiF75Py7FX1DMMejMDiwlS558&callback=initMap">
    </script>

}

CocktailMagicianWeb/Views/Bar/ManageBars.cshtml
@model BarSearchViewModel
@{
    ViewData["Title"] = "ManageBars";
    <style>
        body {
            background-image: url('../images/bar-hd-backgrounds.jpg');
            background-size: cover;
        }

        .BackgroundOpacity {
            margin: 35px;
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 10px 35px;
        }

        h2 {
            margin: 35px;
            font-size: 50px;
        }

        .row {
            margin: 35px;
        }

        h4 {
            padding: 40px 5px 1px 10px;
            font-size: 35px;
        }
    </style>
}

<h2 class="cola">Manage Bars</h2>
<div>
    <form asp-controller="Bar" asp-action="ManageBars">
        <div class="row">
            <input class="form-control col-md-4" placeholder="Bar name..." type="text" asp-for="@Model.Name" />
            <button type="submit" class="btn" style="background-color:#ff0000; color:white" id="searchBtn"><i class="fa fa-search"></i></button>
        </div>
    </form>
</div>

@if (Model != null)
{
    <div class="BackgroundOpacity">

        <h4 class="cola">Search Results.</h4>
        <div asp-validation-summary="All" class="text-danger"></div>


        @if (!(Model.SearchResults.Count == 0))
        {
            <div>

                <table id="barTable" class="table table-hover col-md-10">
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                    </tr>

                    @foreach (var bar in Model.SearchResults)
                    {
                        <tr>
                            @if (bar.CurrentPicture is null)
                            {
                                <td>
                                    <img src="~/images/no-image-icon-6.png" width="230" height="172" />
                                </td>
                            }
                            else
                            {
                                <td>
                                    <img src="data:image/jpg;base64,@(Html.Raw(Convert.ToBase64String(bar.CurrentPicture)))" width="230" height="172" />

                                </td>

                            }
                            <td>@bar.Name</td>
                            <td>
                                <a asp-controller="Bar" asp-action="EditBar" asp-route-id="@bar.Id">Update</a>
                            </td>
                            <td>
                                @if (bar.IsHidden)
                                {
                                    <a id="unhide" data-bar="@bar.Id" asp-controller="" asp-action="">Unhide</a>
                                }
                                else
                                {
                                    <a id="hide" data-bar="@bar.Id" asp-controller="" asp-action="">Hide</a>
                                }
                            </td>
                        </tr>
                    }

                </table>
            </div>
        }
    </div>
}