CocktailMagicianWeb/Models/Cocktails/CocktailViewModel.cs
using CocktailMagician.Data.Entities;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CocktailMagicianWeb.Models.Cocktails
{
    public class CocktailViewModel
    {
        public int Id { get; set; }
        public byte[] Picture { get; set; }
        public IFormFile NewPicture { get; set; }

        [Required, MinLength(3), MaxLength(20, ErrorMessage = "Name must be between 3 and 20 characters.")]
        public string Name { get; set; }
        public bool  IsHidden { get; set; }
        public double Rating { get; set; }
        public List<CocktailReview> CocktailReviews { get; set; } = new List<CocktailReview>();

        [Required, MinLength(2)]
        public List<string> Ingredients { get; set; } = new List<string>(10);
        public List<string> Bars { get; set; } = new List<string>(20);
        [Required, MinLength(1)]
        public List<int> Quantities { get; set; } = new List<int>(10);
    }
}

CocktailMagicianWeb/Models/Cocktails/CocktailsViewModel.cs
using System.Collections.Generic;

namespace CocktailMagicianWeb.Models.Cocktails
{
    public class CocktailsViewModel
    {
        public string Input { get; set; }
        public List<CocktailViewModel> Cocktails { get; set; } = new List<CocktailViewModel>(); 
    }
}

CocktailMagicianWeb/Models/Cocktails/SearchCocktailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Models.Cocktails
{
    public class SearchCocktailViewModel
    {
        public string Name { get; set; }
        public string Ingredient { get; set; }
        public double? AvgRating { get; set; }
        public bool IncludeOnlyAlcoholicDrinks { get; set; }
        public List<CocktailViewModel> SearchResults { get; set; }
       
    }
}

CocktailMagicianWeb/Models/Cocktails/UpdateCocktailViewModel.cs
using CocktailMagicianWeb.Models.Ingredients;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Models.Cocktails
{
    public class UpdateCocktailViewModel
    {
        public int Id { get; set; }
        public byte[] Picture { get; set; }
        public IFormFile NewPicture { get; set; }
        [Required, MinLength(3), MaxLength(15)]
        public string Name { get; set; }
        public bool IsHidden { get; set; }
        [Required, MinLength(2)]
        public List<IngredientViewModel> CurrentIngredients { get; set; } = new List<IngredientViewModel>(10);
        public List<string> Ingredients { get; set; } = new List<string>(20);
        public List<string> OfferingBars { get; set; } = new List<string>(20);
        public List<string> AllBars { get; set; } = new List<string>(20);
        [Required, MinLength(1)]
        public List<int> Quantities { get; set; } = new List<int>(10);
    }
}

CocktailMagicianWeb/Controllers/CocktailsController.cs
using CocktailMagician.Data.Entities;
using CocktailMagician.Services.Contracts;
using CocktailMagicianWeb.Models.Cocktails;
using CocktailMagicianWeb.Utilities.Mappers;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Controllers
{
    public class CocktailsController : Controller
    {
        private readonly IIngredientServices _ingredientServices;
        private readonly ICocktailServices _cocktailServices;
        private readonly ICocktailIngredientServices _cocktailIngredientsServices;
        private readonly IBarCocktailServices _barCocktailServices;
        private readonly IBarServices _barServices;

        public CocktailsController(IIngredientServices ingredientServices, ICocktailServices cocktailServices, ICocktailIngredientServices cocktailIngredientsServices, IBarCocktailServices barCocktailServices, IBarServices barServices)
        {
            _ingredientServices = ingredientServices;
            _cocktailServices = cocktailServices;
            _cocktailIngredientsServices = cocktailIngredientsServices;
            _barCocktailServices = barCocktailServices;
            _barServices = barServices;
        }

        public async Task<IActionResult> ManageCocktails(CocktailsViewModel vm)
        {
            if (string.IsNullOrEmpty(vm.Input))
            {
                return View();
            }

            var viewModel = new CocktailsViewModel();
            var cocktails = await _cocktailServices.GetMultipleCocktailsByNameAsync(vm.Input);
            if (cocktails.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "No cocktails found with this name.");
                return View(viewModel);
            }

            viewModel.Cocktails = cocktails.Select(c => c.MapToViewModel()).ToList();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult AddCocktail()
        {
            return View();
        }

        public async Task<IActionResult> AddCocktail(CocktailViewModel vm)
        {
            if (await _cocktailServices.CocktailWithThatNameExists(vm.Name))
            {
                ModelState.AddModelError(string.Empty, "Cocktail with that name already exists.");
                return View();
            }
            if (vm.NewPicture != null)
            {
                using (var stream = new MemoryStream())
                {
                    await vm.NewPicture.CopyToAsync(stream);
                    vm.Picture = stream.ToArray();
                }
            }
            var cocktail = await _cocktailServices.AddAsync(vm.Name, vm.Picture);
            var ingredients = await _ingredientServices.GetMultipleIngredientsByNameAsync(vm.Ingredients);
            for (int i = 0; i < vm.Quantities.Count; i++)
            {
                await _cocktailIngredientsServices.AddAsync(cocktail, ingredients[i], vm.Quantities[i]);
            }

            foreach (var bar in vm.Bars)
            {
                var barEntity = await _barServices.GetAsync(bar);
                await _barCocktailServices.CreateAsync(barEntity, cocktail);
            }
            return RedirectToAction("UpdateCocktail", new { id = cocktail.Id });
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCocktail(int id)
        {
            var cocktail = await _cocktailServices.GetAsync(id);
            var allBars = await _barServices.GetCollectionAsync();
            var vm = cocktail.MapToViewUpdateModel(allBars);
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCocktail(UpdateCocktailViewModel vm)
        {
            var cocktail = await vm.MapToEntity();
            await _cocktailServices.UpdateCocktailAsync(cocktail);
            var currentIngredients = vm.CurrentIngredients.Select(c => c.MapToEntity()).ToList();
            for (int i = 0; i < currentIngredients.Count; i++)
            {
                if (await _cocktailIngredientsServices.IsPairUpdatedAsync(currentIngredients[i], cocktail, vm.Quantities[i]))
                {
                    if (vm.Quantities[i] == 0)
                    {
                        continue;
                    }

                    await _cocktailIngredientsServices.UpdateAsync(currentIngredients[i], cocktail, vm.Quantities[i]);
                }
            }

            var newIngredients = await _ingredientServices.GetMultipleIngredientsByNameAsync(vm.Ingredients);
            for (int i = 0; i < newIngredients.Count; i++)
            {
                if (!await _cocktailIngredientsServices.PairExistsAsync(newIngredients[i], cocktail))
                {
                    if (vm.Quantities[i] == 0)
                    {
                        continue;
                    }

                    await _cocktailIngredientsServices.AddAsync(cocktail, newIngredients[i], vm.Quantities[i]);
                }
            }

            return View("ManageCocktails");
        }

        public async Task HideCocktail([FromBody]CocktailViewModel vm)
        {
            await _cocktailServices.HideAsync(vm.Id);
        }

        public async Task UnhideCocktail([FromBody]CocktailViewModel vm)
        {
            await _cocktailServices.UnhideAsync(vm.Id);
        }

        public async Task UpdateBarCocktailPairs(string cocktailName, string[] currentlyCheckedBars)
        {
            var cocktail = await _cocktailServices.GetAsync(cocktailName);
            var originalOfferingBars = cocktail.Bars.Select(b => b.Bar).ToList();
            var userCheckBars = new List<Bar>(100);
            foreach (var barName in currentlyCheckedBars)
            {
                var bar = await _barServices.GetAsync(barName);
                userCheckBars.Add(bar);
            }

            var pairsToDelete = originalOfferingBars.Except(userCheckBars);
            var newPairs = userCheckBars.Except(originalOfferingBars);
            foreach (var bar in newPairs)
            {
                await _barCocktailServices.CreateAsync(bar, cocktail);
            }

            foreach (var bar in pairsToDelete)
            {
                await _barCocktailServices.DeleteAsync(bar, cocktail);
            }
        }
        public async Task<IActionResult> GetCocktails()
        {
            var cocktails = await _cocktailServices.GetCollectionAsync();
            return Json(cocktails);
        }
        [HttpGet]
        public IActionResult SearchCocktails()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SearchCocktails(SearchCocktailViewModel viewModel)
        {
            if (viewModel.AvgRating != null)
            {
                viewModel.SearchResults = (await _cocktailServices.SearchByMultipleCriteriaAsync(viewModel.Name, viewModel.Ingredient, viewModel.IncludeOnlyAlcoholicDrinks)).Select(c => c.MapToViewModel()).Where(b => b.Rating == viewModel.AvgRating).ToList();
            }
            else
            {
                viewModel.SearchResults = (await _cocktailServices.SearchByMultipleCriteriaAsync(viewModel.Name, viewModel.Ingredient, viewModel.IncludeOnlyAlcoholicDrinks)).Select(c => c.MapToViewModel()).ToList();
            }
            return View(viewModel);
        }
        public async Task<IActionResult> CocktailDetails(int id)
        {
            var cocktailModel = (await _cocktailServices.GetAsync(id)).MapToViewModel();
            return View(cocktailModel);

        }

        public async Task<IActionResult> NameExists(string name)
        {
            var boolCheck = await _cocktailServices.CocktailWithThatNameExists(name);
            return Json(boolCheck);
        }

        public async Task<IActionResult> LoadMoreBars([FromQuery]int Loaded, [FromQuery]int id)
        {
            var bars = await _cocktailServices.LoadMoreBars(Loaded, id);
            return Json(bars);
        }
    }
}

CocktailMagicianWeb/Controllers/ReviewsController.cs
using CocktailMagician.Data.Entities;
using CocktailMagician.Services.Contracts;
using CocktailMagicianWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CocktailMagicianWeb.Controllers
{

    public class ReviewsController : Controller
    {
        private readonly IBarServices _barServices;
        private readonly IBarReviewServices _barReviewServices;
        private readonly ICocktailReviewServices _cocktailReviewServices;
        private readonly ICocktailServices _cocktailServices;
        private readonly UserManager<User> _userManager;

        public ReviewsController(IBarServices barServices, IBarReviewServices barReviewServices, ICocktailReviewServices cocktailReviewServices, ICocktailServices cocktailServices, UserManager<User> userManager)
        {
            _barServices = barServices;
            _barReviewServices = barReviewServices;
            _cocktailReviewServices = cocktailReviewServices;
            _cocktailServices = cocktailServices;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpGet]
        public async Task<IActionResult> LeaveBarReview(int Id)
        {
            var viewModel = new ReviewViewModel
            {
                Id = Id,
            };
            return View(viewModel);
        }
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpPost]
        public async Task<IActionResult> LeaveBarReview(ReviewViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var bar = await _barServices.GetBarAsync(viewModel.Id);
            await _barReviewServices.CreateBarReviewAsync(viewModel.Rating, viewModel.Comment, bar, user);
            return RedirectToAction("Index", "Home");
        }
 
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpGet]
        public IActionResult LeaveCocktailReview(int Id)
        {
            var viewModel = new ReviewViewModel
            {
                Id = Id,
            };
            return View(viewModel);
        }
        [Authorize(Roles = "BarCrawler, CocktailMagician")]
        [HttpPost]
        public async Task<IActionResult> LeaveCocktailReview(ReviewViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var cocktail = await _cocktailServices.GetAsync(viewModel.Id);
            await _cocktailReviewServices.CreateCocktailReviewAsync(viewModel.Rating, viewModel.Comment, cocktail, user);
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> LoadCoctailReviews(int id)
        {
            var cocktailReviews = await _cocktailReviewServices.GetCocktailReviewsCollectionAsync(id);
            return PartialView("_LoadedCocktailReviewsPartial", cocktailReviews);
        }
        public async Task<IActionResult> LoadBarReviews(int id)
        {
            var reviews = await _barReviewServices.GetBarReviewsCollectionAsync(id);
            return PartialView("_LoadedBarReviewsPartial", reviews);
        }
    }
}

CocktailMagicianWeb/Views/Cocktails/AddCocktail.cshtml
<style type="text/css">
    body {
        background-image: url('../images/smash-ingredients-1000x667.jpg');
        background-size: cover;
    }

    #element1 {
        display: inline-block;
        width: 45%;
        padding: 10px;
    }

    .row {
        border-radius: 16px;
        background-color: rgba(255,250,250,0.7);
        padding: 24px 24px;
        width: 90%;
    }

    #element2 {
        display: inline-block;
        width: 45%;
        padding: 10px;
    }

    .multiselect {
        width: 20em;
        height: 10em;
        border: solid 1px black;
        padding-left: 10px;
        overflow: auto;
    }

        .multiselect label {
            display: block;
        }

    .multiselect-on {
        color: #ffffff;
        background-color: #000099;
    }


    h4 {
        color: black;
        font-size: 45px;
    }
</style>


@model CocktailViewModel
@{
    ViewData["Title"] = "AddCocktail";
}

<h4 class="cola">Add Cocktail</h4>
<div class="row">
    <div class="col-sm-7">
        <form id="Ingredients" class="addCocktail type" asp-controller="Cocktails" asp-action="AddCocktail" enctype="multipart/form-data" data-type="cocktail">
            <input placeholder="Name..." asp-for="@Model.Name" class="form-control col-md-8" id="name">
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <br>
            Image:
            <input type="file" asp-for="NewPicture" />
            <br>
            <br>
            A cocktail must have at least two ingredients.
            <div id="list">
                <button type="button" id="addIngredient" class="btn" style="background-color:#ff0000; color:white"><i class="fa fa-plus-circle"></i></button>
                <br>
                <br>
            </div>
            <br>
            <button id="Submit" type="submit" class="btn" style="background-color:#ff0000; color:white" />Submit
        </form>
    </div>
</div>

@section Scripts
    {
    <partial name="_ValidationScriptsPartial">
}

CocktailMagicianWeb/Views/Cocktails/CocktailDetails.cshtml
@model CocktailViewModel
@{
    ViewData["Title"] = "CocktailDetails";
    <style>

        img {
            max-width: 100%;
            height: auto;
        }

        body {
            background-image: url('../../images/grandhotel_2-1024x683.jpg');
            background-size: cover;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        .margingaps {
            margin: 5px;
        }

        h2 {
            margin-top: 50px;
            margin-left: 20px;
            font-size: 50px;
        }

        .BackgroundOpacity {
            border-radius: 16px;
            background-color: rgba(255,250,250,0.8);
            padding: 35px 35px;
            margin: 20px;
        }

        td{
            background-color: rgba(255,250,250,0.8);
        }

        th {
            width: 100%;
            background-color: #ff0000;
            color: white;
        }

        .buttonReview {
            margin: 5px;
            width: 80%;
            background: #ff0000;
            color: white;
        }


        button {
            background: #ff0000;
        }

        .barDesc {
            background-color: #ff0000;
            color: white;
        }
    </style>
    <link href="~/css/CocktailDetailsGrid.css" rel="stylesheet" />
}





<h2 class="cola">Cocktail Details</h2>

<div class="grid-container">
    <div class="desctipion BackgroundOpacity">
        <div class="picture margingaps">
            @if (Model.Picture != null)
            {
                <img src="data:image/jpg;base64,@(Html.Raw(Convert.ToBase64String(Model.Picture)))" width="500" height="390" />

            }
            else
            {
                <img src="~/images/no-image-icon-6.png" width="230" height="172" />
            }
        </div>
        <div class="googlemaps margingaps">

        </div>
        <div class="info margingaps">
            <table class="table">
                @if (Model != null)
                {
                    <tr>
                        <td class="barDesc">Name:</td>
                        <td>
                            @Model.Name
                        </td>
                    </tr>
                    <tr>
                        <td class="barDesc">Rated:</td>
                        <td>
                            @Model.Rating
                        </td>

                    </tr>
                    <tr>
                        <td class="barDesc">Ingredients:</td>
                        <td>

                            @foreach (var ingredient in Model.Ingredients)
                            {
                                <p>
                                    @ingredient
                                </p>
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="buttons">
            @if (this.User != null)
            {
                <button class="btn buttonReview" color:white" onclick="location.href='@Url.Action("LeaveCocktailReview", "Reviews", new { Id = Model.Id })'">Leave Review</button>
            }
            <button class="btn buttonReview" color:white" id="Load-Cocktails-Reviews" data-cocktail="@Model.Id">Load Reviews</button>

        </div>
        <div class="bars margingaps">
            <table class="table">
                <th>Available In:</th>
                <tr>
                    <td id="InputBars">
                        @foreach (var bar in Model.Bars)
                        {
                            <p class="matataHakuna">@bar</p>
                        }
                    </td>
                </tr>

            </table>
            @if (Model.Bars.Count == 10)
            {
                <button id="load-more-Bars" data-id="@Model.Id">Load More</button>
            }
        </div>
    </div>
    <div id="cocktailCommentBox" class="comments">

    </div>
</div>

CocktailMagicianWeb/Views/Cocktails/ManageCocktails.cshtml
@model CocktailsViewModel
@{
    ViewData["Title"] = "ManageCocktails";
    <style>
        body {
            background-image: url('../../images/royal-cocktails-with-sharing-18100237.jpg');
            background-size: cover;
        }

        .row {
            margin: 35px;
        }

        .BackgroundOpacity {
            margin: 35px;
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 10px 35px;
        }

        h2 {
            margin: 35px;
            font-size: 50px;
        }

        h4 {
            padding: 40px 5px 1px 10px;
            font-size: 35px;
        }
    </style>

}

<h2 class="cola">Manage Cocktails</h2>
<div>
    <form asp-controller="Cocktails" asp-action="ManageCocktails">
        <div class="row">
            <input class="form-control col-md-4" placeholder="Cocktail name..." type="text" asp-for="Input" />
            <button type="submit" class="btn" style="background-color:#ff0000; color:white" id="searchBtn"><i class="fa fa-search"></i></button>
        </div>
    </form>
</div>

@if (Model != null)
{

    <div asp-validation-summary="All" class="text-danger"></div>


    if (!(Model.Cocktails.Count == 0))
    {
        <div class="BackgroundOpacity">
            <h4 class="cola">Search Results.</h4>

            <table id="cocktailTable" class="table table-hover col-md-10">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>

                @foreach (var cocktail in Model.Cocktails)
                {
                    <tr>
                        @if (cocktail.Picture is null)
                        {
                            <td>
                                <img src="~/images/no-image-icon-6.png" width="230" height="172" />
                            </td>
                        }
                        else
                        {
                            <td>
                                <img src="data:image/jpg;base64,@(Html.Raw(Convert.ToBase64String(cocktail.Picture)))" width="230" height="172" />

                            </td>

                        }
                        <td>@cocktail.Name</td>
                        <td>
                            <a asp-controller="Cocktails" asp-action="UpdateCocktail" asp-route-id="@cocktail.Id">Update</a>
                        </td>
                        @if (cocktail.IsHidden)
                        {
                            <td> <a id="unhide" data-cocktail="@cocktail.Id" asp-controller="" asp-action="">Unhide</a></td>
                        }
                        else
                        {
                            <td> <a id="hide" data-cocktail="@cocktail.Id" asp-controller="" asp-action="">Hide</a></td>
                        }
                    </tr>
                }

            </table>
        </div>
    }
}

CocktailMagicianWeb/Views/Cocktails/SearchCocktails.cshtml
@model CocktailMagicianWeb.Models.Cocktails.SearchCocktailViewModel
@{
    ViewData["Title"] = "SearchCoctails";
    <style>
        body {
            background-image: url('../images/royal-cocktails-with-sharing-18100237.jpg');
            background-size: cover;
        }

        .row {
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 35px 35px;
            width: 450px;
        }

        .BackgroundOpacity {
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 10px 35px;
        }
         .form-width {
            width: 250px;
        }
        h2 {
            font-size: 50px;
        }

        h4 {
            padding: 40px 5px 1px 10px;
            font-size: 35px;
        }
    </style>
}

<h2 class="cola">Search Coctails</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="SearchCocktails" class="form-width" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Ingredient" class="control-label"></label>
                <input asp-for="@Model.Ingredient" class="form-control" />
                <span asp-validation-for="@Model.Ingredient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rating</label>
                <input asp-for="@Model.AvgRating" class="form-control" />
                <span asp-validation-for="@Model.AvgRating" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="@Model.IncludeOnlyAlcoholicDrinks" /> Include only alcoholic drinks
                </label>
            </div>
            <div class="search" data-info="Search!">
                <br />
                <button type="submit" class="btn" style="background-color:#ff0000; color:white" id="searchBtn"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
</div>
<br />

@if (Model != null)
{
    <div class="BackgroundOpacity">
        <table class="table table-hover">
            @if (!Model.SearchResults.Any())
            {
                <br />
                <br />
                <br />
                <p class="alert alert-info">There are no bars found!</p>
            }
            else
            {
                <h2 class="cola">Results.</h2>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Ingredients</th>
                </tr>
                @foreach (var cocktail in Model.SearchResults)
                {
                    <tr>

                        @if (cocktail.Picture == null)
                        {
                            <td>
                                <img src="~/images/no-image-icon-6.png" width="230" height="172" />
                            </td>
                        }
                        else
                        {
                            <td>
                                <img src="data:image/jpg;base64,@(Html.Raw(Convert.ToBase64String(cocktail.Picture)))" width="230" height="172" />
                            </td>
                        }
                        <td>
                            @cocktail.Name
                        </td>
                        <td>
                            @foreach (var ingredient in cocktail.Ingredients)
                            {
                                <p>
                                    @ingredient
                                </p>
                            }
                        </td>
                        <td>
                            <button class="btn" style="background-color:#ff0000; color:white" onclick="location.href='@Url.Action("CocktailDetails", "Cocktails", new { Id = @cocktail.Id })'">Details</button>
                        </td>

                    </tr>
                }

            }
        </table>
    </div>
}
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}