CocktailMagicianWeb/Models/Ingredients/AddIngredientViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CocktailMagicianWeb.Models
{
    public class AddIngredientViewModel
    {
        [Required, MinLength(3), MaxLength(20, ErrorMessage = "Name must be between 3 and 20 characters.")]
        public string Name { get; set; }
        public string Type { get; set; }
    }
}

CocktailMagicianWeb/Models/Ingredients/IngredientVIewModel.cs
namespace CocktailMagicianWeb.Models.Ingredients
{
    public class IngredientViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}

CocktailMagicianWeb/Models/Ingredients/IngredientsViewModel.cs
using System.Collections.Generic;

namespace CocktailMagicianWeb.Models.Ingredients
{
    public class IngredientsViewModel
    {
        public string Input { get; set; }
        public List<IngredientViewModel> Ingredients { get; set; } = new List<IngredientViewModel>();
    }
}

CocktailMagicianWeb/Models/Ingredients/UpdateIngredientViemModel.cs
namespace CocktailMagicianWeb.Models.Ingredients
{
    public class UpdateIngredientViemModel
    {
        public int ID { get; set; }
        public string CurrentName { get; set; }
        public string NewName { get; set; }
    }
}

CocktailMagicianWeb/Controllers/IngredientsController.cs
using CocktailMagicianWeb.Models;
using Microsoft.AspNetCore.Mvc;
using CocktailMagician.Services.Contracts;
using System.Threading.Tasks;
using CocktailMagicianWeb.Models.Ingredients;
using System.Linq;
using CocktailMagicianWeb.Utilities;
using Microsoft.AspNetCore.Authorization;
using CocktailMagicianWeb.Utilities.Mappers;

namespace CocktailMagicianWeb.Controllers
{
    public class IngredientsController : Controller
    {
        private readonly IIngredientServices _ingredientServices;
        private readonly ICocktailIngredientServices _cocktailIngredientServices;

        public IngredientsController(IIngredientServices ingredientServices, ICocktailIngredientServices cocktailIngredientServices)
        {
            _ingredientServices = ingredientServices;
            _cocktailIngredientServices = cocktailIngredientServices;
        }

        [HttpGet]
        [Authorize(Roles = "CocktailMagician")]
        public IActionResult ManageIngredients()
        {
            return View();
        }
        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> ManageIngredients(IngredientsViewModel vm)
        {
            var viewModel = new IngredientsViewModel();
            var ingredients = await _ingredientServices.SearchIngredientsAsync(vm.Input);
            if (ingredients.Count() == 0)
            {
                ModelState.AddModelError(string.Empty, "No ingredients found with this name.");
                return View(viewModel);
            }

            viewModel.Ingredients = ingredients.Select(i => i.MapToViewModel()).ToList();
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "CocktailMagician")]
        public IActionResult AddIngredient()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> AddIngredient(AddIngredientViewModel vm)
        {
            if (await _ingredientServices.IngredientWithThatNameExists(vm.Name))
            {
                ModelState.AddModelError(string.Empty, "Ingredient with that name already exists.");
                return View();
            }
            await _ingredientServices.AddAsync(vm.Name, vm.Type);
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> UpdateIngredient(int id)
        {
            var ingredient = await _ingredientServices.GetAsync(id);
            var vm = ingredient.MapToUpdateViewModel();
            return View(vm);
        }

        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> UpdateIngredient(UpdateIngredientViemModel vm)
        {
            await _ingredientServices.UpdateAsync(vm.ID, vm.NewName);
            return View("ManageIngredients");
        }

        [Authorize(Roles = "CocktailMagician")]
        public async Task<IActionResult> DeleteIngredient(int id)
        {
            if (await _ingredientServices.IsIngredientUsedAsync(id))
            {
                ModelState.AddModelError(string.Empty, "The ingredient is currently being used in a cokctail and thus cannot be deleted.");
                return View("ManageIngredients");
            }
            await _ingredientServices.DeleteAsync(id);
            return View("ManageIngredients");
        }

        public async Task RemoveIngredient(string cocktail, string ingredient)
        {
            await _cocktailIngredientServices.DeleteAsync(cocktail, ingredient);
        }

        public async Task<IActionResult> GetIngedientsByType(string type)
        {
            var ingredients = await _ingredientServices.GetIngedientsByTypeAsync(type);

            return Json(ingredients);
        }

        public async Task<IActionResult> NameExists(string name)
        {
            var boolCheck = await _ingredientServices.IngredientWithThatNameExists(name);
            return Json(boolCheck);
        }
    }
}

CocktailMagicianWeb/Views/Ingredients/AddIngredient.cshtml
@model AddIngredientViewModel
@{
    ViewData["Title"] = "AddIngredient";
    <style>
        body {
            background-image: url('../images/ebece441f102d8f8814625cfa24f7fa0.jpg');
            background-size: cover;
        }

        .backgroundOpacity {
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 10px 35px;
            width: 550px;
        }
        .form-width{
            width: 250px;
        }
        h2 {
            font-size: 50px;
        }
    </style>
}

<div class="backgroundOpacity">
<h2 class="cola">Add Ingredient</h2>
<form asp-controller="Ingredients" asp-action="AddIngredient" class="type" data-type="ingredient">
    <div>
        <input id="name" placeholder="Ingredient name..." asp-for="@Model.Name" class="form-control  col-md-4">
        <span asp-validation-for="@Model.Name" class="text-danger"></span>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    Ingredient type:
    <select asp-for="@Model.Type">
        <option value="alcohol  ">Alcoholic</option>
        <option value="sweetener">Sweetener</option>
        <option value="juice">Juice</option>
        <option value="herb">Herb</option>
    </select>
    <br>
    <button id="Submit" class="btn" style="background-color:#ff0000; color:white" />Add
</form>
</div>

CocktailMagicianWeb/Views/Ingredients/ManageIngredients.cshtml
@model IngredientsViewModel
@{
    ViewData["Title"] = "ManageIngredients";
    <style>
        body {
            background-image: url('../../images/ebece441f102d8f8814625cfa24f7fa0.jpg');
            background-size: cover;
        }

        .backgroundOpacity-search {
            margin: 35px;
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 10px 35px;
            width:550px;
        }

        .form-width {
            width: 250px;
        }
          .backgroundOpacity {
            margin: 35px;
            border-radius: 16px;
            background-color: rgba(255,250,250,0.8);
            padding: 10px 35px;
            width:600px;

        }

        h2 {
            font-size: 50px;
        }

        h3 {
            font-size: 35px;
            padding: 10px;
        }
    </style>
}

<div class="backgroundOpacity-search" >
    <h2 class="cola">Manage Ingredients</h2>
    <form asp-controller="Ingredients" asp-action="ManageIngredients">
        <div class="row">
            <input class="form-control col-md-4" placeholder="Ingredient name..." type="text" asp-for="Input" />
            <button type="submit" class="btn" style="background-color:#ff0000; color:white" id="searchBtn"><i class="fa fa-search"></i></button>
        </div>
    </form>
</div>

@if (Model != null)
{

    <div class="backgroundOpacity">

        <h3 class="cola">Search Results.</h3>
        <div asp-validation-summary="All" class="text-danger"></div>
        @if (!(Model.Ingredients.Count == 0))
        {

            <table class="table table-hover col-md-10">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>

                @foreach (var ingredient in Model.Ingredients)
                {
                    <tr>
                        <td>@ingredient.Name</td>
                        <td>@ingredient.Type</td>
                        <td>
                            <a asp-controller="Ingredients" asp-action="UpdateIngredient" asp-route-id="@ingredient.ID">Update</a>
                        </td>
                        <td> <a asp-controller="Ingredients" asp-action="DeleteIngredient" asp-route-id="@ingredient.ID">Delete</a></td>
                    </tr>
                }

            </table>
        }
    </div>
}

CocktailMagicianWeb/Views/Ingredients/UpdateIngredient.cshtml
@model UpdateIngredientViemModel
@{
    ViewData["Title"] = "UpdateIngredient";
    <style>
        body {
            background-image: url('../../images/ebece441f102d8f8814625cfa24f7fa0.jpg');
            background-size: cover;
        }

        .backgroundOpacity {
            border-radius: 16px;
            background-color: rgba(255,250,250,0.7);
            padding: 10px 35px;
        }

        h2 {
            font-size: 50px;
        }
    </style>
}

<div class="backgroundOpacity">
    <h2 class="cola"> Update Ingredient</h2>
    <form asp-controller="Ingredients" asp-action="UpdateIngredient" method="post">
        <input class="form-control col-md-4" value="@Model.CurrentName" type="text" asp-for="@Model.NewName" />
        <button class="btn" style="background-color:#ff0000; color:white" />Update
    </form>
</div>